### ISSUE TITLE
Expand available sensors to mirror iOS functionality more

### ISSUE THREAD

**Issue by jeroenseegers** [home-assistant/android#529]
**Is your feature request related to a problem? Please describe.**
Not directly.

**Describe the solution you'd like**
The iOS companion app enables quite a lot of different sensors to be available when compared to the Android application. It'd be nice to have both companion apps publicize the same sensors.

**Describe alternatives you've considered, if any**
None.

**Additional context**
If compared to the iOS companion app, the following sensors are "missing" from the Android one which I don't believe should be too difficult to implement:
- [x] `sensor.battery_state` (added in #530)
  - This one's currently integrated into the `battery_level` sensor as a `is_charging` property.
- [ ] `sensor.sim1` and `sensor.sim2`
  - If I understand correctly, this information could be requested through the [`SubscriptionManager.getActiveSubscriptionInfoList`](https://developer.android.com/reference/android/telephony/SubscriptionManager.html#getActiveSubscriptionInfoList())
- [ ] `sensor.ssid`
  - This one's currently integrated into the `wifi_connection` sensor as the `state`.
- [ ] `sensor.bssid`
  - This one's currently integrated into the `wifi_connection` sensor as an attribute.
- [ ] `sensor.connection_type`
  - This one could be deducted from the status of the `wifi_connection` sensor, when not connected to a Wi-Fi network this sensor returns `<not connected>` as a state f.e.

I think that making the iOS and Android app align more on these kinds of things would be very nice!

Source of sensor types and availability: https://companion.home-assistant.io/docs/core/sensors

**Comment by dshokouhi** [comment]
I would say maybe we should consider splitting up the requested features but it seems like you have started PR's to add these features :)

**Comment by jeroenseegers** [comment]
We can still split up this task into separate ones per sensor, in that case we'll just edit this one to reflect only the changes to `battery_level` and `battery_state`?

This will also help keeping things a bit more clear in terms of progress I guess.

**Comment by dshokouhi** [comment]
I think that we can leave it as is to avoid breaking changes for users, I think we may be good on this request now with all the new sensors yea?
